# Generated by Django 3.0.3 on 2020-02-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLimit', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19, unique=True)),
                ('dueDate', models.DateField(verbose_name='due date')),
                ('validThru', models.DateField(verbose_name='valid thru')),
                ('name', models.CharField(max_length=40)),
                ('secureCode', models.CharField(max_length=4)),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletApp.Wallet')),
            ],
        ),
    ]
